# Generated by Django 5.2.6 on 2026-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('enunciado', models.TextField()),
                ('opcoes', models.JSONField()),
                ('resposta_correta', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('avg_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('passive', 'Passivo'), ('consumable', 'Consumível')], max_length=15)),
                ('rarity', models.CharField(max_length=20)),
                ('effect_type', models.CharField(max_length=50)),
                ('effect_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('elite', 'Elite')], default='normal', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('topic', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_protected_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_dungeons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='time_spent_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DungeonRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('questions', models.ManyToManyField(related_name='rooms', to='core.fixedquestion')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.weeklydungeon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='UserDungeonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dungeonroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_progress', to='core.profile')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weeklydungeon')),
            ],
            options={
                'unique_together': {('profile', 'dungeon')},
            },
        ),
    ]
