# Generated by Django 5.2.6 on 2026-05-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fixedquestion_item_weeklydungeon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_dungeons_completed',
            new_name='total_elite_dungeons_completed',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_normal_dungeons_completed',
            field=models.IntegerField(default=0),
        ),
    ]
