# Generated by Django 5.2.6 on 2026-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_total_dungeons_completed_profile_total_elite_dungeons_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hp',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_hp',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(default='amber', max_length=20),
        ),
    ]
