# Generated by Django 5.2.6 on 2026-05-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_font_size_profile_hp_profile_max_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='current_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='activatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='max_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='recovery_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_combo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_combo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
