# Generated by Django 5.2.6 on 2026-05-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventoryitem_current_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='dungeon_type',
            field=models.CharField(default='normal', max_length=15),
        ),
    ]
