# Generated by Django 5.2.6 on 2026-05-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_questionhistory_dungeon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydungeon',
            name='level_required',
            field=models.IntegerField(default=1),
        ),
    ]
