# Generated by Django 5.2.6 on 2026-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_weeklydungeon_level_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdungeonprogress',
            name='max_combo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdungeonprogress',
            name='session_gold_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdungeonprogress',
            name='session_xp_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdungeonprogress',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdungeonprogress',
            name='total_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdungeonprogress',
            name='total_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
