# Generated by Django 5.2.6 on 2026-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userdungeonprogress_max_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydungeon',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
    ]
